#!/bin/bash
apt-get update && apt-get install -y curl

# content for this start file, except for curl install, copied from https://github.com/pyvista/pyvista-tutorial/tree/gh-pages/binder
export PYVISTA_TRAME_SERVER_PROXY_PREFIX="$JUPYTERHUB_SERVICE_PREFIX/proxy/"
exec "$@"